baseURL = "https://xxxasdfghjk.github.io/"
languageCode = "ja-jp"
title = "xxxasdfghjk's blog"
theme = 'github-style'


[params]
  author = "xxxasdfghjk"
  avatar = "/images/avatar.jpg"
  description = "Done is better than perfect"
  github = "xxxasdfghjk"
  twitter = "xxxasdfghjk"
  email = "xxxasdfghjk999@gmail.com"
  favicon = "/images/github.png"
  location = "Japan"
  userStatusEmoji = "👺"
  enableGitalk = true
   [params.gitalk]
    clientID = "a01378ceca3845e834d0" 
    clientSecret = "35821df1b2b465c700c1f2a76f11ccc8ba30583f" 
    repo = "pages-comment-store"
    owner = "xxxasdfghjk"
    admin = "xxxasdfghjk"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 30
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false